name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NAME: "Prafull"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node-version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Print .npmrc before
        run: |
          npm cache clean --force
          cat .npmrc

      - name: Install dependencies and list directory
        run: |
          npm install
          ls -l
          ls -a
          
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          PASSWORD: "Hello, World!"
          NAME: ${{env.NAME}}
      
        
      - name: Print .npmrc after
        run: |
          echo "value of the NMAE is:${{env.NAME}}"
          cat .npmrc
      
      - name: print .npmrc variables
        run: |
          npm config get name
          npm config get password
          npm config get registry
          npm config get always-auth
          npm config get _authtoken
