name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node-version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Print .npmrc before
        run: |
          cat .npmrc

      - name: Install dependencies and list directory
        run: |
          npm install
          ls -l
          ls -a
          echo "Token: ${{secrets.NPM_TOKEN}}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
      - name: Print .npmrc after
        run: |
            cat .npmrc
