name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NAME: "Prafull"
  HELLO: "Hello, World!"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node-version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Print .npmrc before
        run: |
          npm cache clean --force
          cat .npmrc

      - name: Install dependencies and list directory
        run: |
          npm install
          ls -l
          ls -a
          npm config get name
          npm config get hello
          npm config get registry
          
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          HELLO: ${{env.HELLO}}
          NAME: ${{env.NAME}}
      
        
      - name: Print .npmrc after
        run: |
          cat .npmrc
      
      - name: print .npmrc variables
        run: |
          npm config get name
          npm config get hello
          npm config get registry

